name: Autoupdate Fastfetch

on:
  workflow_dispatch:
  schedule:
    - cron: "15 4 * * *"

permissions:
  contents: write
  pull-requests: write

jobs:
  check_new_releases:
    name: Check for new releases
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check versions
        run: |
          CURRENT=$(cat src/fastfetch.json | jq -r .version)
          LATEST=$(curl -s -S -H "Authorization: Bearer ${{ github.token }}" https://api.github.com/repos/fastfetch-cli/fastfetch/releases | jq -r .[0].tag_name)
          echo "current=${CURRENT}" >> "$GITHUB_ENV"
          echo "latest=${LATEST}" >> "$GITHUB_ENV"

      - name: Do update
        if: ${{ env.current != env.latest }}
        run: |
          sed -i 's/${{ env.current }}/${{ env.latest }}/g' src/fastfetch.json

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          committer: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          commit-message: 'Bump Fastfetch to ${{ env.latest }}'
          title: '[🤖] Bump Fastfetch to ${{ env.latest }}'
          body: Automatically generated PR - Bumping Fastfetch from ${{ env.current }} to ${{ env.latest }}
          branch: bump-fastfetch
          delete-branch: true